#
#server:  
#  port: 8090 

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
#        app-downloaded-in:
#          destination: appDownloaded
#          contentType: application/json
#          group: cacheGroup
        app-downloaded-out:
          destination: appDownloaded
          contentType: application/json
